CC = g32

all: Exe 

Exe : req1.o req2.o req3.o req4.o

	$(CC) -o req1.o Sequence.cpp testSequence.cpp
	$(CC) -o req2.o newSequence.cpp testnewSequence.cpp
	$(CC) -o req3.o Sequence.cpp LevelList.cpp testLevelList.cpp
	$(CC) -o req4.o newSequence.cpp LevelList.cpp testLevelList.cpp
	./req1.o
	./req2.o
	./req3.o
	./req4.o

clean:
	rm *.o